#pragma once

#include "rdr2_include/ActionContext.hpp"
#include "rdr2_include/AmmoComponent.hpp"
#include "rdr2_include/animAnimatorComponent.hpp"
#include "rdr2_include/aniRide.hpp"
#include "rdr2_include/bhPacketExec.hpp"
#include "rdr2_include/bhWeaponsPacket.hpp"
#include "rdr2_include/camCamera.hpp"
#include "rdr2_include/camCameraChannel.hpp"
#include "rdr2_include/camCameraTransitionBase.hpp"
#include "rdr2_include/CameraViewport.hpp"
#include "rdr2_include/camManager.hpp"
#include "rdr2_include/ConditionMoverNotOnGround.hpp"
#include "rdr2_include/eCodeSideStatistics.hpp"
#include "rdr2_include/eState.hpp"
#include "rdr2_include/eWeaponAction.hpp"
#include "rdr2_include/gohCamera.hpp"
#include "rdr2_include/gohCameraFactory.hpp"
#include "rdr2_include/gohDofSettings.hpp"
#include "rdr2_include/grcViewport.hpp"
#include "rdr2_include/hlthHealthComponent.hpp"
#include "rdr2_include/hlthMsgInjure.hpp"
#include "rdr2_include/invInventoryComponent.hpp"
#include "rdr2_include/invWeaponType.hpp"
#include "rdr2_include/mvrMoverComponent.hpp"
#include "rdr2_include/ProjectileLaunchData.hpp"
#include "rdr2_include/projProjectile.hpp"
#include "rdr2_include/rdrActorTracker.hpp"
#include "rdr2_include/rdrMatrixAudioEntity.hpp"
#include "rdr2_include/sagActor.hpp"
#include "rdr2_include/sagGuid.hpp"
#include "rdr2_include/sagLayout.hpp"
#include "rdr2_include/sagPlayer.hpp"
#include "rdr2_include/tgtReticleComponent.hpp"
#include "rdr2_include/TransitionCamera.hpp"
#include "rdr2_include/weapBaseWeaponType.hpp"
#include "rdr2_include/WeaponParams.hpp"
#include "rdr2_include/WeaponSpecialRequest.hpp"
#include "rdr2_include/weapProjectileInfo.hpp"
#include "rdr2_include/weapWeapon.hpp"

namespace rdr2
{
	sagActor *const GetPlayerActor();
	camManager *const GetCamManager();
}